name: Build and Deploy
on:
    push:
        branches:
            - master
jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   name: Build and Deploy
                uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.2
                with:
                    github_access_token: ${{ secrets.GITHUB_TOKEN }}
                    build_configuration: production
                    base_href: /grand-tichu/
                    deploy_branch: gh-pages
                    angular_dist_build_folder: dist/grand-tichu
